// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Gunakan sessionStorage untuk development (session terpisah per tab)
// Gunakan localStorage untuk production (session dibagikan antar tab)
const isDevelopment = import.meta.env.DEV;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isDevelopment ? sessionStorage : localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});